name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.x'
      - name: Test
        run: ./gradlew api:check
      - name: Build PR
        run: ./gradlew api:assemble
        env:
          HEAD_BRANCH: ${{ github.head_ref }}
        if: github.event_name == 'pull_request'
      - name: Build
        run: ./gradlew api:assemble
        env:
          HEAD_BRANCH: main
        if: github.event_name == 'push'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: rdfpoker-api.jar
          path: api/build/libs/api-0.0.1-SNAPSHOT.jar

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 13.x
      - name: NPM CI Install
        run: npm ci
        working-directory: ./ui
      - name: Unit Tests
        run: npm run test-ci
        working-directory: ./ui
      - name: Build
        run: npm run build
        working-directory: ./ui
      - name: Zip Build
        run: zip -r rdfpoker-ui.zip build
        working-directory: ./ui
      - name: Release artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: rdfpoker-ui.zip
          path: ui/rdfpoker-ui.zip
    
